#pragma once

#include "VFX.hpp"
#include "BloomPass.hpp"
#include "OpticalFlowPass.hpp"
#include "CRTPass.hpp"
#include "EdgePass.hpp"
#include "Symmetry.hpp"
#include "StreakPass.hpp"
#include "NoiseWarpPass.hpp"
#include "CAPass.hpp"
#include "InvertPass.hpp"
#include "ZoomBlurPass.hpp"
#include "MNCAPass.hpp"
#include "InkPass.hpp"
